import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillFacebook, AiFillGithub,} from 'react-icons/ai';
import {FiMail, FiPhone} from 'react-icons/fi';
import {TfiLocationPin} from 'react-icons/tfi';
import photo from '../public/photo.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';

import {useState} from "react"; 
import Text from './TextEffects';
import Education from './Education';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className= {darkMode ? "dark" : "" }>
      <Head>
        <title>Katarzyna Węsierska Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 md:mx-20 lg:px-40 dark:bg-gray-900">
        <section>
        <nav className="py-10 mb-12 flex justify-between dark:text-white">
          <h1 className="text-md dark:text-white lg:text-lg">Hello, I'm</h1>
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode) } className="cursor-pointer"/>
            </li>
            <li><a className="bg-gradient-to-r from-cyan-300 to-teal-600 px-4 py-2 rounded-md ml-8" href="./public/cv.pdf" download="cv.pdf">CV</a></li>
          </ul>
        </nav>
        <div className="">
           <h5 className="text-4xl font-medium text-center md:font-10xl dark:text-white"> 
           <Text/>
           </h5>
          <h3 className="text-3md text-center pt-6 text-cyan-500 md:font-5xl" >Junior Front-End Developer</h3>
          </div>
        <div className="relative mx-auto bg-gradient-to-b from-yellow-400 rounded-full w-80 h-80 mt-10 overflow-hidden">
        <Image className="mx-auto" src={photo} layout="fill" objectFit="cover" alt="Photo"/>
        </div>
        </section>

        <section>
       <div className="py-8 text-left">
       <h3 className="text-2xl py-2 dark:text-white">About me</h3>

        <p className="text-sm leading-5 dark:text-white">I am a Computer Science student at <span className="text-orange-800" > PJAIT
        in Gdańsk </span>(4th year). I am a passionate Junior Front-End Developer interested in building beautiful, functional and mobile-friendly websites. I know the basics of HTML/CSS and JavaScript. Currently learning ReactJs. My strong skills are creativity, communication and being a team player. I am motivated to learn and ready for new challenges.</p>
       <Education/>
      </div>
        </section>
        <h3 className="text-xl py-5 dark:text-white">Technologies</h3>
        <section className="py-3 flex justify-around md:px-30">
       <div className="shadow-lg p-10 rounded-xl dark:bg-slate-300">
        <h2 className="text-md text-center text-cyan-500 pt-2 pb-2 py-1 hover:scale-120">Front-End</h2>
        <p className="text-left">HTML</p>
        <p className="text-left">CSS</p>
        <p className="text-left">JavaScript</p>
        <p className="text-left">React</p>
        </div>

        <div className="shadow-lg p-10 rounded-xl  dark:bg-slate-300">
        <h2 className="text-md text-cyan-500 pt-2 pb-2 py-1  hover:scale-120 dark:bg-grey-500">Back-end</h2>
        <p className="text-left">Java</p>
        <p className="text-left">Spring Boot</p>
        <p className="text-left">C#</p>
        <p className="text-left">.NET</p>
        </div>
        <div className=" shadow-lg p-10 rounded-xl dark:bg-slate-300 hover:scale-120">
        <h2 className="text-md text-cyan-500 pt-2 pb-2 py-1">Others</h2>
        <p className="text-left">MySQL</p>
        <p className="text-left">Visual Studio Code</p>
        <p className="text-left">Intelij</p>
        <p className="text-left">WebStorm</p>
        </div>
        </section>

        <section>
          <div>
            <h3 className="text-2xl py-2 dark:text-white">My projects</h3>
            <p className="text-sm py-2 leading-5 dark:text-white">In my project I use HTML, CSS (TailwindCSS), JavaScript with React.js, Node.js and Next.js. 
              I still learn new technologis and freameworks. 
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image alt="Photo" src={web1} className="rounded-lg object-cover" layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
            <Image alt="Photo" src={web3} className="rounded-lg object-cover"  layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
            <Image alt="Photo" src={web2} className="rounded-lg object-cover"  layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
            <Image alt="Photo" src={web4} className="rounded-lg object-cover"  layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
            <Image alt="Photo" src={web1} className="rounded-lg object-cover"  layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
            <Image alt="Photo" src={web1} className="rounded-lg object-cover" layout="responsive"/>
            </div>
          </div>
        </section>
        <h3 className="text-2xl py-2  dark:text-white">Contact</h3>
        <section className="flex justify-around ">
        <div className="">
        <p className="text-cyan-500 text-xl p-5" >Katarzyna Węsierska</p>
        <p className="dark:text-white flex p-2"><TfiLocationPin className="mx-2"/> Gdańsk, Poland</p>
        <p className="dark:text-white flex  p-2"><FiMail className="mx-2"/> +48 724 744 833</p>
        <p className="dark:text-white flex p-2"><FiPhone className="mx-2"/> kasiamlynska@op.pl</p>
        </div>
        <div>
        <p className="dark:text-white  p-3">Find me on:</p>
        <div className="text-4xl flex justify-center gap-8 py-3 dark:text-white">
        <AiFillLinkedin className="hover:scale-150"/>
        <AiFillFacebook className="hover:scale-150"/>
        <AiFillGithub className="hover:scale-150"/>
        </div>
        </div>
        </section>
      </main> 
      <footer className="p-4">
        <p className="text-center text-sm">Katarzyna Węsierska 2022</p>
      </footer>
    </div>
  )
}
