import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillFacebook} from 'react-icons/ai';
import photo from '../public/photo.png';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Katarzyna Węsierska Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="bg-white">
        <nav className="py-10 mb-12 flex justify-between ">
          <h1 className="text-md">Hello, I'm</h1>
          <ul className=" flex items-center">
            <li>
              <BsFillMoonStarsFill className="cursor-pointer"/>
            </li>
            <li><a className="bg-gradient-to-r from-cyan-300 to-teal-600 text-white px-4 py-2 rounded-md ml-8" href="#">CV</a></li>
          </ul>
        </nav>
        <div className=" ">
        
          <h2 className="text-3xl font-medium text-center">Katarzyna Węsierska</h2>
          <h3 className="text-3md text-center pt-6 text-cyan-500" >Junior Front-End Developer</h3>
          </div>
        <div className="relative mx-auto bg-gradient-to-b from-yellow-400 rounded-full w-80 h-80 mt-10 overflow-hidden">
        <Image className="mx-auto" src={photo} layout="fill" objectFit="cover" alt="Photo"/>
        </div>
        </section>
        <section>
       <div className="py-8 text-left">
       <h3 className="text-2xl py-2">About me</h3>

        <p className="text-sm leading-5">I am a Computer Science student at <span className="text-orange-800" > PJAIT
        in Gdańsk </span>(4th year). I am a passionate Junior Front-End Developer interested in building beautiful, functional and mobile-friendly websites. I know the basics of HTML/CSS and JavaScript. Currently learning ReactJs. My strong skills are creativity, communication and being a team player. I am motivated to learn and ready for new challenges.</p>
                
      </div>
        </section>
        <section className="py-3">
        <h3 className="text-center text-lg font-medium  text-cyan-500 pt-2 pb-2 py-1">Technologies</h3>
      
        <div className=" text-center shadow-lg p-10 rounded-xl">
        <h2 className="text-md text-cyan-500 pt-2 pb-2 py-1">Front-End</h2>
        <p>HTML</p>
        <p>CSS</p>
        <p>JavaScript</p>
        <p>React</p>
        </div>
        <div className=" text-center shadow-lg p-10 rounded-xl">

        <h2 className="text-md text-cyan-500 pt-2 pb-2 py-1">Back-end</h2>
        <p>C++</p>
        <p>Java</p>
        <p>C#</p>
        <p>.NET</p>
        </div>
        </section>
        <section>
          <div>
            <h3 className="text-2xl py-2">My projects</h3>
            <p className="text-sm py-2 leading-5">In my project I use HTML, CSS (TailwindCSS), JavaScript with React.js, Node.js and Next.js. 
              I still learn new technologis and freameworks. 
            </p>
          </div>
        </section>
        <h3 className="text-2xl py-2">Contact with me</h3>

        <div className="text-4xl flex justify-center gap-16 py-3">
        <AiFillLinkedin/>
        <AiFillFacebook/>
        </div>
      </main> 
    </div>
  )
}
